
const TypesOfErrors = {
  UNKNOWN_ERROR: 0,
  ROUTING_ERROR: 1,
  INVALID_TYPE_ERROR: 2,
  DATABASE_ERROR: 3,
  INVALID_PARAM_ERROR: 4,
  AUTHENTICATION_ERROR: 5,
  AUTHORIZATION_ERROR: 6,
  TOKEN_ERROR: 7,
}

module.exports = TypesOfErrors;